[package]
name = "cli"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
dep-resolver = { path = "../dep-resolver" }
environment = { path = "../environment" }
manifests = { path = "../manifests" }
structopt = "0.3.25"
