[package]
name = "dep-resolver"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
manifests = { path = "../manifests" }
environment = { path = "../environment" }
toml = "0.5.8"

[dev-dependencies]
mockall = "0.10.2"
